kumuluzee:
  name: Filme
  version: 1.0.0
  env:
    name: dev
  datasources:
    - jndi-name: jdbc/filmeDS
      connection-url: jdbc:postgresql://localhost:5432/filme
      username: postgres
      password: postgres
      max-pool-size: 20
  dev:
    scan-libraries:
      - entitete
      - storitve

zunanjiApi: https://search.imdbot.workers.dev/